# Generated by Django 5.2.6 on 2025-09-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcombo',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_combos', to='vendors.combo'),
        ),
        migrations.AddField(
            model_name='featuredcombo',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_combos', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='quickmenu',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_menus', to='vendors.combo'),
        ),
        migrations.AddField(
            model_name='quickmenu',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_menus', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='vendors.vendor'),
        ),
        migrations.AddConstraint(
            model_name='featuredcombo',
            constraint=models.UniqueConstraint(fields=('vendor', 'combo'), name='unique_featuredcombo_vendor_combo'),
        ),
        migrations.AddConstraint(
            model_name='quickmenu',
            constraint=models.UniqueConstraint(fields=('vendor', 'combo'), name='unique_quickmenu_vendor_combo'),
        ),
    ]
