# Generated by Django 5.2.6 on 2025-09-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('menuitem', '0004_remove_combo_base_chutney_remove_combo_base_idli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcombo',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_combos', to='menuitem.combo'),
        ),
        migrations.AlterField(
            model_name='quickmenu',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_menus', to='menuitem.combo'),
        ),
    ]
