# Generated by Django 5.2.6 on 2025-09-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0002_initial'),
        ('vendors', '0004_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('idli', 'Idli'), ('chutney', 'Chutney'), ('sambar', 'Sambar'), ('other', 'Other')], default='timenow', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Idli Plate', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_idli', models.PositiveIntegerField(default=4)),
                ('base_chutney', models.PositiveIntegerField(default=2)),
                ('base_sambar', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=80, max_digits=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_combos', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ComboRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg: 4 idli + chutney + sambar', max_length=100)),
                ('required_idli', models.PositiveIntegerField(default=4)),
                ('required_chutney', models.PositiveIntegerField(default=3)),
                ('required_sambar', models.PositiveIntegerField(default=1)),
                ('combo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_rules', to='vendors.vendor')),
            ],
        ),
    ]
