# Generated by Django 5.2.6 on 2025-09-21 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0003_rename_available_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='base_chutney',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='base_idli',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='base_sambar',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='vendor',
        ),
        migrations.AddField(
            model_name='combo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='combo',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='combo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
