# Generated by Django 5.2.6 on 2025-09-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0004_remove_combo_base_chutney_remove_combo_base_idli_and_more'),
        ('vendors', '0005_alter_comboitem_combo_alter_combovendor_combo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='is_available',
        ),
        migrations.AddField(
            model_name='combo',
            name='base_chutney',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='combo',
            name='base_idli',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='combo',
            name='base_sambar',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='combo',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_combos', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(default='Idli Plate', max_length=100),
        ),
        migrations.AlterField(
            model_name='combo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
    ]
