# Generated by Django 5.2.6 on 2025-09-22 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0005_remove_combo_created_at_remove_combo_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
