# Generated by Django 5.2.6 on 2025-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0006_combo_created_at_combo_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
