# Generated by Django 5.2.6 on 2025-09-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0007_combo_code'),
        ('vendors', '0005_alter_comboitem_combo_alter_combovendor_combo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='vendor',
        ),
        migrations.AddField(
            model_name='combo',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='menuitem_combos', to='vendors.vendor'),
        ),
    ]
