# Generated by Django 5.2.6 on 2025-09-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0010_menuitem_fiber_alter_menuitem_calories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
    ]
