# Generated by Django 5.2.6 on 2025-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0011_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comborule',
            name='required_chutney',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
