# Generated by Django 5.2.6 on 2025-09-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuitem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/')),
                ('details', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('signature_dish', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendors/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('menu_card', models.FileField(blank=True, null=True, upload_to='menu_cards/')),
                ('owner_name', models.CharField(default='Unknown', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('items_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.combo')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_combo_items', to='menuitem.menuitem')),
            ],
            options={
                'verbose_name': 'Combo Item',
                'verbose_name_plural': 'Combo Items',
                'unique_together': {('combo', 'menu_item')},
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='menu_items',
            field=models.ManyToManyField(related_name='combos', through='vendors.ComboItem', to='menuitem.menuitem'),
        ),
        migrations.CreateModel(
            name='ComboVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.combo')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Combo Vendor',
                'verbose_name_plural': 'Combo Vendors',
                'unique_together': {('combo', 'vendor')},
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='vendors',
            field=models.ManyToManyField(related_name='combos', through='vendors.ComboVendor', to='vendors.vendor'),
        ),
    ]
