# Generated by Django 5.2.6 on 2025-09-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_featuredcombo_combo_alter_quickmenu_combo'),
        ('menuitem', '0004_remove_combo_base_chutney_remove_combo_base_idli_and_more'),
        ('orders', '0002_alter_orderitem_combo'),
        ('vendors', '0004_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboitem',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='menuitem.combo'),
        ),
        migrations.AlterField(
            model_name='combovendor',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuitem.combo'),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuitem.menuitem'),
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
