# Generated by Django 5.2.6 on 2025-09-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('vendors', '0003_alter_vendor_city_alter_vendor_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendors.vendor'),
        ),
    ]
