# Generated by Django 5.2.6 on 2025-09-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0003_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Pending'), ('placed', '✅ Placed'), ('preparing', '👨\u200d🍳 Preparing'), ('on_the_way', '🚚 On the Way'), ('delivered', '🎉 Delivered'), ('cancelled', '❌ Cancelled')], default='pending', max_length=20),
        ),
    ]
